export const ROUTE_PERMISSIONS = {
  dashboard: ['Dashboard.read'],
  products: ['Product.read'],
  productCreate: ['Product.create'],
  productUpdate: ['Product.update'],
  categories: ['Category.read'],
  categoryCreate: ['Category.create'],
  categoryUpdate: ['Category.update'],
  banners: ['Banner.read'],
  bannerCreate: ['Banner.create'],
  bannerUpdate: ['Banner.update'],
  orders: ['Order.read'],
  orderUpdate: ['Order.update'],
  payments: ['Payment.read'],
  paymentVerify: ['Payment.verify'],
  paymentReject: ['Payment.reject'],
  shipments: ['Shipment.read'],
  shipmentCreate: ['Shipment.create'],
  shipmentUpdate: ['Shipment.update'],
  promos: ['Promo.read'],
  promoCreate: ['Promo.create'],
  promoUpdate: ['Promo.update'],
  users: ['User.read'],
  userUpdate: ['User.update'],
  roles: ['Role.read'],
  roleCreate: ['Role.create'],
  roleUpdate: ['Role.update'],
} as const;

